name: wf-build-and-test

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make

      - name: Add MSYS2 to PATH
        run: echo "::add-path::C:\\msys64\\mingw64\\bin"

      - name: Configure CMake
        run: cmake -G "MinGW Makefiles" -B build

      - name: Build
        run: mingw32-make -C build

      - name: Run tests
        run: build\\CompanyProjectTests.exe --success
